### ISSUE TITLE
Missing crossorigin in preload links

### ISSUE THREAD

**Issue by iloveip** [NoriSte/gatsby-plugin-preload-link-crossorigin#351]
Hi there,
I have installed your plugin, but I still get the following warnings in Lighthouse:

```
A preload <link> was found for "http://localhost:9000/component---src-pages-index-mdx-e6ed278a64857e149e0f.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/1be01058e1f3014a1acddec0dc53296c1d20dfd8-9bb2f306fcd610d49295.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/styles-8636a280cbc61d53ad10.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/app-b991cd848746e17373f4.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/framework-984c7a17186e83dc1ff4.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/webpack-runtime-bc1b15ddcbf885ce7042.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/page-data/index/page-data.json" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.

A preload <link> was found for "http://localhost:9000/page-data/app-data.json" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```

**Comment by NoriSte** [comment]
Hi @iloveip 
Could you tell me which version of Gatsby and Lighthouse are you using, please? Have you [added the plugin to the config](https://github.com/NoriSte/gatsby-plugin-preload-link-crossorigin#how-to-use)? I have just run a test and everything seems ok...
Thanks
Stefano

**Comment by iloveip** [comment]
Hi Stefano,

Yes, I have added the plugin to `gatsby-confih.js`. I have `"gatsby": "^2.20.12",`. I'm running Lighthouse from Google Chrome of the latest version.

I have the following links in my `head`:

```
<link as="script" rel="preload" href="/webpack-runtime-bb5c22958388d5e7e941.js" crossorigin="">
<link as="script" rel="preload" href="/framework-984c7a17186e83dc1ff4.js" crossorigin="">
<link as="script" rel="preload" href="/app-ed8dab2e6603061cf4d5.js" crossorigin="">
<link as="script" rel="preload" href="/styles-8636a280cbc61d53ad10.js" crossorigin="">
<link as="script" rel="preload" href="/1be01058e1f3014a1acddec0dc53296c1d20dfd8-6e5e5607c0e02502bffb.js" crossorigin="">
<link as="script" rel="preload" href="/component---src-pages-calculator-mdx-4852e8acc893c65a24cc.js" crossorigin="">
<link as="fetch" rel="preload" href="/page-data/calculator/page-data.json" crossorigin="anonymous">
<link as="fetch" rel="preload" href="/page-data/app-data.json" crossorigin="anonymous"> 
```

**Comment by NoriSte** [comment]
Since I don't see the same error... Could you share with me a minimal repo removing everything yours until remain just the bare Gatsby project with the plugin and nothing more? And I'd like to know even the lighthouse (and chrome) version please, thanks Svetlana 😊

**Comment by cbdp** [comment]
Hi @NoriSte and @iloveip, I was getting similar errors. 
```
Chrome version 83.0.4103.97 
Gatsby version: 2.22.19
Lighthouse version: 5.7.1
```
example of the error: 
```
A preload <link> was found for "mysite/webpack-runtime-25a516c495d69823af5e.js" but was not used by the browser. Check that you are using the `crossorigin` attribute properly.
```
head has:
```
<link as="script" rel="preload" href="/webpack-runtime-25a516c495d69823af5e.js" crossorigin="">
```
But at the bottom of body, I've also got:
```
<script src="/webpack-runtime-25a516c495d69823af5e.js" async=""></script>
```
Could the bottom async be throwing off Lighthouse 5.7.1?

Since I'm on the latest official build of Chrome, I wrongly assumed Lighthouse would follow suit. However, a new version of lighthouse was released in May, version 6.0.0, so I installed that with npm, ran it against my site and the error disappeared. So I'm not sure it's an issue with the plugin, but rather with lighthouse, if that makes sense.

One other thing tho: After enabling the plugin and placing it dead last in my gatsby-config in order for it to work, I got a new preload error on both versions of lighthouse:
```
Preconnect to required origins: https://fonts.googleapis.com
```
I'm using a font preload plugin and I was wondering, if maybe that plugin implements the same API as yours and if so, could that cause only one of them to work at a time?

Thank you for all your hard work :)

**Comment by NoriSte** [comment]
> Since I'm on the latest official build of Chrome, I wrongly assumed Lighthouse would follow suit. However, a new version of lighthouse was released in May, version 6.0.0, so I installed that with npm, ran it against my site and the error disappeared. So I'm not sure it's an issue with the plugin, but rather with lighthouse, if that makes sense.

Yep, that's why I asked about the Lighthouse version, I know that sometimes there are different versions out there because of the Chrome releases, etc.

I think we should keep the thing monitored and please let me know if you got similar errors in the next days/weeks.

> I'm using a font preload plugin and I was wondering, if maybe that plugin implements the same API as yours and if so, could that cause only one of them to work at a time?

They could interfere, maybe a blacklist option could be added to my plugin? Could you check what your preload plugin adds to the page?

> Thank you for all your hard work :)

Thank you for the detailed feedback 😊

**Comment by cbdp** [comment]
You're welcome 😊 

The plugin I'm using for preloading fonts is: https://www.gatsbyjs.org/packages/gatsby-plugin-preload-fonts/ 

While I'm still new to react (and gatsby!) I'm guessing the relevant part of the code is this:
```
  setHeadComponents(
    assets.map(href => {
      let assetProps

      // External urls should get the props from the plugin configuration.
      // Local urls will be forced with `crossOrigin: "anonymous"`
      try {
        // check if URL is external, if not this constructor throws.
        new URL(href)
        assetProps = props
      } catch (e) {
        assetProps = { crossOrigin: `anonymous` }
      }

      return (
        <link key={href} as="font" href={href} rel="preload" {...assetProps} />
      )
    })
  )
}
```

**Comment by NoriSte** [comment]
Yes, it would be possible and good IMO, a sorting of "all" the possible `as` values would be useful and, based on your feedback and other users feedback we could choose which kind of options add (`as`-based blacklist? Domain-based blacklist? Regex-based blacklist?) because @iloveip feedback was different...

**Comment by iloveip** [comment]
Sorry for such late reply. I was also running Lighthouse version 5.7.1 from the Chrome. And I also had async scripts at the bottom. I've downloaded the latest version of Lighthouse from npm and the error disappeared.

@cbdp Thank you very much for your help!

**Comment by cbdp** [comment]
@NoriSte Based on your experience, what would be the path of least resistance? 
I would be tempted by the as="" blacklist option, but I worry it's not quite standard in both plugins and the code people write themselves. RegEx based blacklisting seems to be asking for trouble, but it might be easiest to implement? Domain-based blacklisting was my initial first idea, but now I worry about people self-hosting fonts. Might just be regEx is the way to go? Or simply the option to blacklist not domains, but entire urls. Sorry if that's what you meant, like I said, I'm new :)

@iloveip You're welcome, but all credit goes to NoriSte ;)

**Comment by NoriSte** [comment]
@cbdp regex is hard and "unpredictable", the easiest solution is the domain-based one (take a look at my [preconnect plugin options](https://github.com/NoriSte/gatsby-plugin-preconnect)) but it has the disadvantages you listed...

In the end, regexes could be the most complete, future-proof, solution...

**Comment by cbdp** [comment]
@NoriSte Maybe if a few short RegEx examples were added to your docs to help out us users?

Then something like 
```
export const onPreRenderHTML = ({
  getHeadComponents,
  replaceHeadComponents,
}, options) => {
  const components = getHeadComponents();
  const regex = ^((?!EXAMPLE1|EXAMPLE2).)*$
  for(let i = 0, n = components.length; i < n; i++) {
    const component = components[i];
    if(component.type === "link" && component.props && component.props.rel === "preload" && component.match(regex)) {
      component.props.crossorigin = "";
    }
  }
  replaceHeadComponents(components);
}
```

**Comment by NoriSte** [comment]
What if we opt for [minimatch](https://github.com/isaacs/minimatch)? It's the same used by Cypress for its [cy.route matching](https://docs.cypress.io/api/commands/route.html#Wait-on-url-matching-glob).

**Comment by cbdp** [comment]
Did not know about minimatch, seems like a great project for those of us who are regexally challenged 😄  I say go for it

**Comment by NoriSte** [comment]
Then the last two things:
- blacklist or whitelist? I think the former is better because if you are in trouble it's probably because
  1. you want to add `crossorigin` to all the links, that's why you are using this plugin (I hope)
  2. some links give bother you and you'd like to exclude them
Could you think of some more use cases?

- I probably can't work on it this month, if you hurry a PR is more than welcome 😊

Thanks for discussing 😊

**Comment by cbdp** [comment]
I'll look into it, but I'm not promising anything, so don't get too excited 😆 

Thanks for a great discussion, I learned a lot and even if I can't work out how to fix it in a PR, it's been extremely helpful. 👍

**Comment by NoriSte** [comment]
My pleasure, it's interesting for me too 😊 looking for your contribution... 😉😁
